import {test,expect} from '@playwright/test';
const read=page=>page.evaluate(()=>window.__CLIMBER_TEST__?.snapshot());
test('C0.3: dynamic viewport and aspect updates immediately without reload',async({page})=>{
 test.setTimeout(60_000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:844});
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25000}).toBe(true);
 const first=await read(page);
 expect(first.viewportW).toBe(390);
 expect(first.viewportH).toBe(844);
 const baseline=first.resizeEvents;
 for(const [width,height] of [[900,440],[360,800],[700,700]]){
  await page.setViewportSize({width,height});
  await expect.poll(async()=>(await read(page))?.viewportW,{timeout:8000}).toBe(width);
  await expect.poll(async()=>(await read(page))?.viewportH,{timeout:8000}).toBe(height);
  const s=await read(page);
  expect(s.resizeEvents).toBeGreaterThan(baseline);
  expect(Math.abs(s.renderWidth/s.renderHeight-width/height)).toBeLessThan(.025);
  expect(Math.abs(s.canvasClientWidth/s.canvasClientHeight-width/height)).toBeLessThan(.025);
 }
 await page.screenshot({path:'test-results/c03-square-after-live-resize.png'});
 expect(errors).toEqual([]);
});
test('C0.3: no self-climb; one stronger swipe; true Bullet danger and summit emitter',async({page})=>{
 test.setTimeout(100_000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25000}).toBe(true);
 let s=await read(page);
 expect(s.slopeDegrees).toBe(60);
 expect(s.rampCollider).toBe('static');
 expect(s.rigidbodyType).toBe('dynamic');
 expect(s.mysteryVisible).toBe(true);
 expect(s.emitterProgress).toBeGreaterThan(s.slopeLength);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.elapsed,{timeout:15000}).toBeGreaterThan(.9);
 s=await read(page);
 expect(s.forwardFlicks).toBe(0);
 expect(s.maxProgress).toBeLessThan(3.6);
 for(let i=0;i<7;i++){
  await page.keyboard.press('ArrowUp');
  await page.waitForTimeout(230);
 }
 await expect.poll(async()=>(await read(page))?.maxProgress,{timeout:12000}).toBeGreaterThan(5);
 s=await read(page);
 expect(s.forwardFlicks).toBeGreaterThanOrEqual(5);
 expect(s.maxForwardSpeed).toBeGreaterThan(3.2);
 expect(s.cameraY).toBeLessThan(s.y+2);
 expect(s.cameraZ).toBeGreaterThan(s.z+5);
 expect(s.falls).toBeGreaterThanOrEqual(0);
 await page.keyboard.press('ArrowRight');
 await expect.poll(async()=>(await read(page))?.sideFlicks,{timeout:3000}).toBeGreaterThan(0);
 await page.screenshot({path:'test-results/c03-uphill-mystery.png'});
 expect(errors).toEqual([]);
});
test('C0.3: physical crates + spheres, summit-only avalanche, trains, giant masses and clean disposal',async({page})=>{
 test.setTimeout(120_000);
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25000}).toBe(true);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.spawnWaves,{timeout:85000,intervals:[300,400,650]}).toBeGreaterThanOrEqual(12);
 const s=await read(page);
 expect(s.spawnedTotal).toBeGreaterThan(30);
 expect(s.totalBox).toBeGreaterThan(0);
 expect(s.totalSphere).toBeGreaterThan(0);
 expect(s.totalRock).toBeGreaterThan(0);
 expect(s.totalLoot).toBeGreaterThan(0);
 expect(s.patterns.train).toBeGreaterThan(0);
 expect(s.patterns['loot-train']).toBeGreaterThan(0);
 expect(s.patterns.giant).toBeGreaterThan(0);
 expect(s.giantsSpawned).toBeGreaterThan(0);
 expect(s.maxRockMass).toBeGreaterThan(25);
 expect(s.maxRocks).toBe(50);
 expect(s.maxLoot).toBe(50);
 expect(s.activeCap).toBe(100);
 expect(s.peakRocks).toBeLessThanOrEqual(50);
 expect(s.peakLoot).toBeLessThanOrEqual(50);
 expect(s.liveRocks).toBeLessThanOrEqual(50);
 expect(s.liveLoot).toBeLessThanOrEqual(50);
 expect(s.maxLive).toBeLessThanOrEqual(100);
 await expect.poll(async()=>(await read(page))?.destroyedTotal,{timeout:35000}).toBeGreaterThan(0);
 const t=await read(page);
 expect(t.destroyedTotal+t.liveFalling).toBe(t.spawnedTotal);
 await page.screenshot({path:'test-results/c03-giant-wave.png'});
});
test('C0.3: pointer flick emits one torque/forward impulse, no continuous drive',async({page})=>{
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25000}).toBe(true);
 await page.locator('#start').click();
 await page.mouse.move(175,620);await page.mouse.down();
 await page.mouse.move(175,480,{steps:4});await page.mouse.up();
 await expect.poll(async()=>(await read(page))?.forwardFlicks,{timeout:3500}).toBe(1);
 await page.waitForTimeout(450);
 expect((await read(page)).forwardFlicks).toBe(1);
 await page.mouse.move(165,560);await page.mouse.down();
 await page.mouse.move(290,560,{steps:4});await page.mouse.up();
 await expect.poll(async()=>(await read(page))?.sideFlicks,{timeout:3500}).toBe(1);
});
