import {test,expect} from '@playwright/test';
const read=page=>page.evaluate(()=>window.__CLIMBER_TEST__?.snapshot());
test('C0.2: real 60 degree physical ramp, NO self climb, discrete impulse rolls',async({page})=>{
 test.setTimeout(90_000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25_000}).toBe(true);
 const initial=await read(page);
 expect(initial.slopeDegrees).toBe(60);
 expect(initial.rampCollider).toBe('static');
 expect(initial.rigidbodyType).toBe('dynamic');
 expect(initial.levelHeight).toBeGreaterThan(40);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.elapsed,{timeout:15_000}).toBeGreaterThan(1.0);
 const idle=await read(page);
 expect(idle.forwardFlicks).toBe(0);
 expect(idle.maxProgress).toBeLessThan(3.6);
 expect(idle.elapsed).toBeGreaterThan(1.0);
 for(let i=0;i<10;i++){
  await page.keyboard.press('ArrowUp');
  await page.waitForTimeout(190);
 }
 const climbed=await read(page);
 expect(climbed.forwardFlicks).toBeGreaterThanOrEqual(8);
 expect(climbed.maxProgress).toBeGreaterThan(5);
 expect(climbed.rigidbodyType).toBe('dynamic');
 expect(climbed.cameraY).toBeLessThan(climbed.y+1.0);
 expect(climbed.cameraZ).toBeGreaterThan(climbed.z+5);
 expect(climbed.totalRock).toBeGreaterThan(0);
 expect(climbed.totalLoot).toBeGreaterThan(0);
 await page.screenshot({path:'test-results/c02-sixty-degree-chase.png'});
 await page.keyboard.press('ArrowRight');await page.waitForTimeout(220);
 expect((await read(page)).sideFlicks).toBeGreaterThan(0);
 expect(errors).toEqual([]);
});
test('C0.2: endless wave lifecycle, mixed physics shapes, bounded live objects',async({page})=>{
 test.setTimeout(95_000);
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25_000}).toBe(true);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.spawnWaves,{timeout:35_000}).toBeGreaterThanOrEqual(6);
 const middle=await read(page);
 expect(middle.totalBox).toBeGreaterThan(0);
 expect(middle.totalSphere).toBeGreaterThan(0);
 expect(middle.spawnedTotal).toBeGreaterThan(15);
 expect(middle.maxLive).toBeLessThanOrEqual(middle.activeCap);
 await expect.poll(async()=>(await read(page))?.destroyedTotal,{timeout:23_000}).toBeGreaterThan(2);
 const after=await read(page);
 expect(after.spawnWaves).toBeGreaterThanOrEqual(6);
 expect(after.patterns.row).toBeGreaterThan(0);
 expect(after.patterns.train).toBeGreaterThan(0);
 expect(after.patterns['loot-row']).toBeGreaterThan(0);
 expect(after.liveFalling).toBeLessThanOrEqual(after.activeCap);
 expect(after.destroyedTotal+after.liveFalling).toBe(after.spawnedTotal);
 await page.screenshot({path:'test-results/c02-dynamic-rows-and-loot.png'});
});
test('C0.2: pointer swipe fires exactly once and does not enable continuous auto motion',async({page})=>{
 await page.goto('/');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:25_000}).toBe(true);
 await page.locator('#start').click();
 await page.mouse.move(185,610);
 await page.mouse.down();
 await page.mouse.move(185,495,{steps:5});
 await page.mouse.up();
 await expect.poll(async()=>(await read(page))?.forwardFlicks,{timeout:3_000}).toBe(1);
 await page.waitForTimeout(800);
 expect((await read(page)).forwardFlicks).toBe(1);
 await page.mouse.move(185,590);await page.mouse.down();
 await page.mouse.move(280,590,{steps:3});await page.mouse.up();
 await expect.poll(async()=>(await read(page))?.sideFlicks,{timeout:3_000}).toBe(1);
});
